
.PHONY: download-dumps
download-dumps:
	curl -O https://www.edsm.net/dump/systemsWithCoordinates7days.json.gz
	curl -O https://www.edsm.net/dump/systemsWithoutCoordinates.json.gz
	curl -O https://www.edsm.net/dump/systemsPopulated.json.gz
	curl -O https://www.edsm.net/dump/powerPlay.json.gz
	curl -O https://www.edsm.net/dump/stations.json.gz
	curl -O https://www.edsm.net/dump/codex.json.gz
	curl -O https://www.edsm.net/dump/bodies7days.json.gz
